### ISSUE TITLE
execution script needs shebang at start of file

### ISSUE THREAD

**Issue by pgordon9** [mikeyhu/scaladiagrams#12]
## Error
When running `./scaladiagrams` from within a `fish` shell I get the following error:

```sh
pgordon@Parkers-MBP ~/g/scaladiagrams> ./scaladiagrams
Failed to execute process './scaladiagrams'. Reason:
exec: Exec format error
The file './scaladiagrams' is marked as an executable but could not be run by the operating system.
```
## Resolution
Make sure a shebang character sequence is placed at the beginning of the start script `./scaladiagrams` during its generation

**Comment by mikeyhu** [comment]
Closing this now as #13 has fixed the issue.
