### ISSUE TITLE
How to generate the diagrams in Windows.

### ISSUE THREAD

**Issue by gabrielacosta** [mikeyhu/scaladiagrams#5]
Hi Mikey,

Sorry to bother you. I want to use your project in Windows.

I compile it using the command build.sbt.
And it's scaladiagrams file. I try to add the sbt file to the new scaladiagrams.sbt and run it again. But, It is not working. 
I'm learning scala and sbt, could you please tell me how can use it in Windows.

Kind regards, 

Juan

**Comment by mikeyhu** [comment]
Hi there,

The executable 'scaladiagrams' is just a bash script that provides any arguments to the java runtime that runs the jar. In windows you could run the program just by :

java -jar target\scala-2.9.2\scaladiagrams-assembly-1.0.jar YOUR_ARGUMENTS > TARGET_DOT_FILE

I don't have a windows machine to test this on but something like that should generate you a dot file that you can then use with Graphviz for Windows.

Next time I'm on a windows machine I'll look at writing a batch file for this.

Mike.

**Comment by gabrielacosta** [comment]
Hi Mikey, 

Thank you for your answer, but I realize the build wasn't working properly. So at the end what I done is use git command bash (installed git and added the bash functions in windows).

![build](https://cloud.githubusercontent.com/assets/8519425/9460488/ec90d93c-4b49-11e5-8122-726bd8492422.png)

That allows me to build the jar file scaladiagrams-assembly-1.0.jar
Installed GraphzWiz 2.8 in Windows and added the path in the environment variables.

With all in place,  try to run the your command but it was given me errors in the path. So, I moved the jar to the same level and used with the next command:

java -jar scaladiagrams-assembly-1.0.jar --source C:\Code\Development\t-server\app | dot.exe -Tsvg > file.svg

![command](https://cloud.githubusercontent.com/assets/8519425/9460499/feb58f36-4b49-11e5-9759-9891570e9452.png)

I leave the process here, meanwhile you create the batch file, as another option to use your app.

I like your tool a lot, thanks for everything.

Kind regards,

Juan
